services:
  - type: web
    name: steel-defect-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS false
    plan: free
